package com.avsystem.commons
package rpc

/**
 * Runtime base for proxies generated by [[RpcDerivation.materializeAsRaw]]. Holds the
 * underlying `real` instance that the generated Raw subclass dispatches to.
 */
abstract class RpcProxyBase[Real](val real: Real)
